In [12]:
import os, random, sys, time
# from urllib.parse import urlparse
from selenium import webdriver
from bs4 import BeautifulSoup
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
import pandas as pd
from selenium.common.exceptions import NoSuchElementException
from statsmodels.tsa.seasonal import seasonal_decompose
import statsmodels.api as sm
import numpy as np
import copy
from langdetect import detect
from googletrans import Translator
from LinkedIn_Scraper1 import scrape_linkedin
from Glassdoor_Scraper1 import scrape_glassdoor
from Detect_New_Entries import merge_new_entires, detect_new_entires
import time
date_string = time.strftime("%Y-%m-%d-%Hh")

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

Initializing LinkedIn scraper...
New Leads in Excel Scraping Translated: 17

KeyboardInterrupt:

# Creates the big file

In [24]:

# revenue_df = pd.read_excel('Scrapping revenue.xlsx')       # File from scrape_glassdoor
# original_leads = pd.read_excel('data/All_data.xlsx')

# original_leads = pd.read_csv('data/All_data.csv')
lkdin_df

       Unnamed: 0                                           Name                                         Web_Name                             Website           Phone                              Industry           Company size                  Headquarters                     Type  Founded                                        Specialties  Translated?                                        Translation
0               0                                         abb ag                                           ABB AG                                 NaN             NaN                  Consumer Electronics        11-50 employees                           NaN                      NaN      NaN                                                NaN          1.0                                                NaN
1               1                     grupo tice ingenieros s.l.                            Grupo TICE Ingenieros             http://www.grupotice.es     34961554072  Mechanical Or Industrial Engineering        11-50 employees  Torrent, Valencian Community           Public Company   2006.0  Gestión Integral de Almacenes, Marcado CE, Cál...          1.0  Integral Warehouse Management, CE, Structural ...
2               2              johnson matthey technology centre                         Maxsys Fuel Systems Ltd.            http://www.maxsysltd.com             NaN                          Oil & Energy        11-50 employees           Telford, Shropshire           Privately Held   2004.0  Annual energy cost savings between 3 and 7%, T...          1.0  Annual energy cost savings between 3 and 7%, T...
3               3                                lumi industries                                  Lumi Industries        http://www.lumindustries.com             NaN                     Computer Hardware         2-10 employees              Montebelluna, TV           Privately Held   2014.0  stampa 3d, prototipazione rapida, resina fotos...          1.0  3D printing, rapid prototyping photosensitive ...
4               4                              oldtimerparts gbr                                              NaN                                 NaN             NaN                                   NaN                    NaN                           NaN                      NaN      NaN                                                NaN          1.0                                                NaN
...           ...                                            ...                                              ...                                 ...             ...                                   ...                    ...                           ...                      ...      ...                                                ...          ...                                                ...
28218          55  Budapest University of Technology & Economics  Budapest University of Technology and Economics                  http://www.bme.hu/  +36 1 463 1111                      Higher Education  1,001-5,000 employees                           NaN  Educational Institution      NaN                                                NaN          NaN                                                NaN
28219          56                          Zanini auto grup, sau                                              NaN                                 NaN             NaN                                   NaN                    NaN                           NaN                      NaN      NaN                                                NaN          NaN                                                NaN
28220          57           Schneider International Holding GmbH             Schneider International Holding GmbH  http://schneider-international.net             NaN                            Automotive                    NaN                           NaN                      NaN      NaN                                                NaN          NaN                                                NaN
28221          58                                      Intech 3D                                         INTECH3D              http://www.intech3d.es             NaN  Mechanical Or Industrial Engineering         2-10 employees                Lleida, Lleida      Sole Proprietorship   2016.0  Impresión 3D, Formación 3D, Prototipaje, Serie...          NaN                                                NaN
28222          59                                        SEDECAL                                          SEDECAL              http://www.sedecal.com             NaN                        Medical Device  1,001-5,000 employees                Algete, Madrid           Privately Held   1994.0  electromedicina, OEM, generadores de alta frec...          NaN                                                NaN

[28223 rows x 13 columns]

New Leads: 0

# Detect language

In [38]:
# DETECT LANGUAGE
#############################################################
def detect_language(lkdin_df):
    languages = []
    for speciality in lkdin_df["Specialties"]:
        if pd.isnull(speciality):
            languages.append("NoText")
        else:
            string = str(speciality)
            languages.append(detect(string))
    return languages

# Translate Speciallities

In [40]:
def generate_Resultats_Verticals_Linkedin(path, file):
    
    merge_new_entires(path,file) # Example: ("data","data26-4-20")
    scrape_glassdoor(path,file)
    scrape_linkedin(path,file)

    # READ
    lkdin_df = pd.read_excel('Excel Scraping Translated.xlsx') # File from scrape_linkedin
    df_to_transl = lkdin_df[lkdin_df["Translated?"]!=1]
    print("New Leads:",len(df_to_transl))

    # DETECT LANGUAGE
    languages = detect_language(df_to_transl)
    df_to_transl['Languages'] = np.array(languages)

    # TRANSLATE COMENTS
    list_specialities = df_to_transl[df_to_transl["Languages"]!= "en"] # NOT ENGLISH
    list_specialities = list_specialities[list_specialities['Languages']!="NoText"] # NOT NAN
    print("Leads that need to be translated:", len(list_specialities))
    translatedList = translate_list(list_specialities)

    # JOIN THE TRANSLATED PART TO THE ORIGINAL DATAFRAME
    df_to_transl = df_to_transl.drop(["Translation"], axis=1)
    df_translation = pd.DataFrame(translatedList, columns=["Original","Translation"])
    df_to_transl2 = df_to_transl.merge(df_translation, left_on='Specialties', right_on='Original', how='left')
    df_to_transl2['Translation'] = df_to_transl2['Translation'].fillna(df_to_transl2['Specialties'])
    df_to_transl3 = df_to_transl2.drop(columns="Original")
    df_to_transl3["Translated?"] = 1

    # MERGE DATAFRAMES AGAIN
    already_transl = lkdin_df[lkdin_df["Translated?"]==1]
    lkdin_df3 = already_transl.append(df_to_transl3)
    lkdin_df3.to_excel("Excel Scraping Translated.xlsx")
    lkdin_df3.to_excel(f'backups_scrape/Excel Scraping Translated{date_string}.xlsx')


    # MERGE
    revenue_df = pd.read_excel('Scrapping revenue.xlsx')       # File from scrape_glassdoor
    original_leads = pd.read_excel('data/All_data.xlsx')
    original_leads['Company'] = original_leads['Company'].str.lower()

    revenue_df = revenue_df[['Name','Tamaño','Sector','Ingresos']]
    revenue_df = revenue_df.rename(columns={"Name": "Company",
                                        "Tamaño": "GlsDr_Company size",
                                        "Sector": "GlsDr_Industry",
                                        "Ingresos": "GlsDr_Income"})
    revenue_df['Company'] = revenue_df['Company'].str.lower()

    lkdin_df3 = lkdin_df3[['Name','Web_Name','Industry','Company size','Headquarters','Specialties', 'Translation']]
    lkdin_df3 = lkdin_df3.rename(columns={"Name": "Company",
                                        "Industry": "LkdIn_Industry",
                                        "Web_Name": "LkdIn_Web_Name",
                                        "Company size": "LkdIn_Company_size",
                                        "Headquarters": "LkdIn_Headquarters",
                                        "Specialties": "LkdIn_Specialties",
                                         "Translation" : "LkdIn_Translation"})
    lkdin_df3['Company'] = lkdin_df3['Company'].str.lower()

    result = lkdin_df3.merge(original_leads, left_on='Company', right_on='Company', how='right')

    result = result.merge(revenue_df, left_on='Company', right_on='Company', how='left')
    print('\nResult:',len(result))
    print("Qualifieds", len(result[result['Lead Status']=='Qualified']))
    print("Nurtures", len(result[result['Lead Status']=='Nurture']))

    result.to_excel("Resultats Verticals Linkedin10.xlsx")
    result.to_excel(f'backups_scrape/Resultats Verticals Linkedin{date_string}.xlsx')

Leads that need to be translated: 0

In [29]:
# TRANSLATE
##############################################################
def translate_list(list_specialities):
    translatedList = []
    for speciality in list_specialities["Specialties"]:
        temporal_place = []
        # ORIGINAL STRING
        temporal_place.append(speciality)

        # REINITIALIZE THE API
        translator = Translator()
        time.sleep(round(random.uniform(1, 2),2))

        try:
            # TRANSLATE
            temporal_place.append(translator.translate(speciality, dest='en').text)
        except Exception as e:
            print(str(e))
            temporal_place.append("")
            continue

        translatedList.append(temporal_place)
        print(len(translatedList),"-",round(len(translatedList)/len(list_specialities)*100,2),"% completed.")
    return translatedList

1 - 1.03 % completed.
2 - 2.06 % completed.
3 - 3.09 % completed.
4 - 4.12 % completed.
5 - 5.15 % completed.
6 - 6.19 % completed.
7 - 7.22 % completed.
8 - 8.25 % completed.
9 - 9.28 % completed.
10 - 10.31 % completed.
11 - 11.34 % completed.
12 - 12.37 % completed.
13 - 13.4 % completed.
14 - 14.43 % completed.
15 - 15.46 % completed.
16 - 16.49 % completed.
17 - 17.53 % completed.
18 - 18.56 % completed.
19 - 19.59 % completed.
20 - 20.62 % completed.
21 - 21.65 % completed.
22 - 22.68 % completed.
23 - 23.71 % completed.
24 - 24.74 % completed.
25 - 25.77 % completed.
26 - 26.8 % completed.
27 - 27.84 % completed.
28 - 28.87 % completed.
29 - 29.9 % completed.
30 - 30.93 % completed.
31 - 31.96 % completed.
32 - 32.99 % completed.
33 - 34.02 % completed.
34 - 35.05 % completed.
35 - 36.08 % completed.
36 - 37.11 % completed.
37 - 38.14 % completed.
38 - 39.18 % completed.
39 - 40.21 % completed.
40 - 41.24 % completed.
41 - 42.27 % completed.
42 - 43.3 % completed.
43 - 44.33 % completed.
44 - 45.36 % completed.
45 - 46.39 % completed.
46 - 47.42 % completed.
47 - 48.45 % completed.
48 - 49.48 % completed.
49 - 50.52 % completed.
50 - 51.55 % completed.
51 - 52.58 % completed.
52 - 53.61 % completed.
53 - 54.64 % completed.
54 - 55.67 % completed.
55 - 56.7 % completed.
56 - 57.73 % completed.
57 - 58.76 % completed.
58 - 59.79 % completed.
59 - 60.82 % completed.
60 - 61.86 % completed.
61 - 62.89 % completed.
62 - 63.92 % completed.
63 - 64.95 % completed.
64 - 65.98 % completed.
65 - 67.01 % completed.
66 - 68.04 % completed.
67 - 69.07 % completed.
68 - 70.1 % completed.
69 - 71.13 % completed.
70 - 72.16 % completed.
71 - 73.2 % completed.
72 - 74.23 % completed.
73 - 75.26 % completed.
74 - 76.29 % completed.
75 - 77.32 % completed.
76 - 78.35 % completed.
77 - 79.38 % completed.
78 - 80.41 % completed.
79 - 81.44 % completed.
80 - 82.47 % completed.
81 - 83.51 % completed.
82 - 84.54 % completed.
83 - 85.57 % completed.
84 - 86.6 % completed.
85 - 87.63 % completed.
86 - 88.66 % completed.
87 - 89.69 % completed.
88 - 90.72 % completed.
89 - 91.75 % completed.
90 - 92.78 % completed.
91 - 93.81 % completed.
92 - 94.85 % completed.
93 - 95.88 % completed.
94 - 96.91 % completed.
95 - 97.94 % completed.
96 - 98.97 % completed.
97 - 100.0 % completed.

## Merge Dataframes Again

In [ ]:
# lkdin_df3.to_excel("Excel Scraping Translated.xlsx")
# lkdin_df3.to_excel(f'backups_scrape/Excel Scraping Translated{date_string}.xlsx')

## General

Result: 37361
Qualifieds 2025
Nurtures 3115

In [ ]:
result